
--CREATE DATABASE LOVOLUXE;

--USE LOVOLUXE;

CREATE TABLE Race
(
ID INT IDENTITY (1,1) PRIMARY KEY,
Race VARCHAR(30) NOT NULL
);


CREATE TABLE Director
(
ID INT IDENTITY (1,1) PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
MiddleName VARCHAR(30) NULL,
Surname VARCHAR(30) NOT NULL,
Age FLOAT NULL, 
Gender VARCHAR(10) NOT NULL,
RaceID INT FOREIGN KEY REFERENCES Race(ID), 
StartDate DATE NOT NULL,
EndDate DATE NULL,
AddressLine1 VARCHAR(60) NOT NULL, 
AddressLine2 VARCHAR(60) NULL,
City VARCHAR(30) NOT NULL,
Province VARCHAR(30) NOT NULL,
ZipCode VARCHAR(10) NOT NULL,
Country VARCHAR(30) NOT NULL,
Email VARCHAR(60) NOT NULL,
ContactNumber1 VARCHAR(30) NOT NULL,
ContactNumber2 VARCHAR(30) NULL,
CreatedDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE SalesPerson
(
ID INT IDENTITY (1,1) PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
MiddleName VARCHAR(30) NULL,
Surname VARCHAR(30) NOT NULL,
Age FLOAT NULL, 
Gender VARCHAR(10) NOT NULL,
RaceID INT FOREIGN KEY REFERENCES Race(ID),
StartDate DATE NOT NULL,
AddressLine1 VARCHAR(60) NOT NULL, 
AddressLine2 VARCHAR(60) NULL,
City VARCHAR(30) NOT NULL,
Province VARCHAR(30) NOT NULL,
ZipCode VARCHAR(10) NOT NULL,
Country VARCHAR(30) NOT NULL,
Email VARCHAR(60) NOT NULL,
ContactNumber1 VARCHAR(30) NULL,
ContactNumber2 VARCHAR(30) NULL,
CreatedDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE Supplier
(
ID INT PRIMARY KEY, 
Name VARCHAR(30) NOT NULL,
ContactName VARCHAR(30) NULL,
ContactNumber VARCHAR(30) NULL,
URL_Address NVARCHAR(250) NULL,
AddressLine1 VARCHAR(60) NULL,
AddressLine2 VARCHAR(60) NULL,
City VARCHAR(30) NULL,
Province VARCHAR(30) NULL,
ZipCode VARCHAR(10) NULL,
Country VARCHAR(30) NOT NULL,
ContactPersonName VARCHAR(30) NULL,
ContactPersonNumber VARCHAR(30) NULL,
Email VARCHAR(60) NULL,
ContactNumber VARCHAR(30) NULL,
CreatedDate DATETIME DEFAULT GETDATE()
)

CREATE TABLE Customer
(
ID INT IDENTITY (1,1) PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
MiddleName VARCHAR(30) NULL,
Surname VARCHAR(30) NULL,
AddressLine1 VARCHAR(60) NOT NULL, 
AddressLine2 VARCHAR(60) NULL,
City VARCHAR(30) NOT NULL,
Province VARCHAR(30) NOT NULL,
ZipCode VARCHAR(10) NOT NULL,
Country VARCHAR(30) NOT NULL,
Email VARCHAR(60) NULL,
ContactNumber VARCHAR(30) NULL,
CreatedDate DATETIME DEFAULT GETDATE()
);


CREATE TABLE Size
(
ID INT IDENTITY (1,1) PRIMARY KEY,
GeneralSize NVARCHAR(10) NOT NULL,
TrouserSize NVARCHAR(10) NULL,
WaistSize_cm NVARCHAR(10) NULL,
BustSize_cm NVARCHAR(10) NULL,
HipsSize_cm NVARCHAR(10) NULL,
);

CREATE TABLE PrimaryColour
(
PrimaryColourID INT IDENTITY (1,1) PRIMARY KEY,
Colour VARCHAR(30) NOT NULL
);

CREATE TABLE SecondaryColour
(
SecondaryColourID INT IDENTITY (1,1) PRIMARY KEY,
Colour VARCHAR(30) NOT NULL
);

CREATE TABLE LogoColour
(
LogoColourID INT IDENTITY (1,1) PRIMARY KEY,
Colour VARCHAR(30) NOT NULL
);

CREATE TABLE ProductStatus
(ID INT PRIMARY KEY IDENTITY (1,1),
ProductStatus VARCHAR(30) NOT NULL
);

CREATE TABLE Product
(
ID INT IDENTITY (1,1) PRIMARY KEY,
LOVOProductName VARCHAR(255) NOT NULL,
SupplierProductName VARCHAR(255) NOT NULL,
ProductCode VARCHAR (60) NULL,
SupplierID INT FOREIGN KEY REFERENCES Supplier(ID),
SizeID INT FOREIGN KEY REFERENCES Size(ID),
PrimaryColourID INT FOREIGN KEY REFERENCES PrimaryColour(PrimaryColourID) NOT NULL,
SecondaryColourID INT FOREIGN KEY REFERENCES SecondaryColour(SecondaryColourID),
LogoColourID INT FOREIGN KEY REFERENCES LogoColour(LogoColourID),
LogoSize_PositionDescription VARCHAR (255) NULL,
ProductDescription VARCHAR(255) NULL,
ProductCost FLOAT NOT NULL,
ShippingCost FLOAT NULL,
CustomisationCost FLOAT NOT NULL,
PackagingCost FLOAT NOT NULL,
Customs FLOAT NULL,
TotalUnitCost FLOAT NOT NULL,
ListingPrice FLOAT NOT NULL,
ExpectedMarkUp FLOAT NOT NULL,
InventoryOnHand INT NULL,
ProductStatusID INT FOREIGN KEY REFERENCES ProductStatus(ID), 
CreatedDate DATETIME DEFAULT GETDATE()
);


CREATE TABLE SalesOrderHeader
(
SalesOrderID INT IDENTITY (1001,1) PRIMARY KEY,
OrderDate Date NOT NULL,
ShipDate Date NOT NULL,
CarrierTrackingNumber VARCHAR(60),
CustomerID INT FOREIGN KEY REFERENCES Customer(ID),
AddressLine1 VARCHAR(60) NOT NULL, 
AddressLine2 VARCHAR(60) NULL,
City VARCHAR(30) NOT NULL,
Province VARCHAR(30) NOT NULL,
ZipCode VARCHAR(10) NOT NULL,
Country VARCHAR(30) NOT NULL,
SubTotal FLOAT,
ShippingCost FLOAT,
OrderDiscount FLOAT,
TotalDue FLOAT,
CreatedDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE SalesOrderDeatail
(
SalesOrderDetailID INT IDENTITY (0001,1) PRIMARY KEY,
SalesOrderID INT FOREIGN KEY REFERENCES SalesOrderHeader(SalesOrderID),
Quantity INT NOT NULL, 
ProductID INT FOREIGN KEY REFERENCES Product(ID),
UnitPrice FLOAT NOT NULL,
UnitPriceDiscount FLOAT NOT NULL, 
LineTotal FLOAT NOT NULL,
CreatedDate DATETIME DEFAULT GETDATE()
);






















